version: "3.4"
services:
  bai_vite:
    container_name: bai_vite
    build:
      context: ./root
      dockerfile: ../Dockerfile
    ports:
      - 8005:8005
    volumes:
      - ./root:/app
      - /app/node_modules
      - /app/dist
